export const PERFUMES = {
  data: [
    {
      id: 1,
      perfumeName: '가19',
      brandName: 'ga',
      category: '시트러스',
      imageUrl: '',
      option: '오 드 퍼퓸',
      price: 240000,
      capacity: '100ml',
      scraped: true,
    },
    {
      id: 2,
      perfumeName: '나19',
      brandName: 'na',
      category: '시트러스',
      imageUrl: '',
      option: '오 드 퍼퓸',
      price: 240000,
      capacity: '100ml',
      scraped: false,
    },
    {
      id: 3,
      perfumeName: '다29',
      brandName: 'da',
      category: '스파이시',
      imageUrl: '',
      option: '오 드 퍼퓸',
      price: 240000,
      capacity: '100ml',
      scraped: true,
    },
    {
      id: 4,
      perfumeName: '라29',
      brandName: 'ra',
      category: '레더',
      imageUrl: '',
      option: '오 드 퍼퓸',
      price: 240000,
      capacity: '100ml',
      scraped: true,
    },
    {
      id: 5,
      perfumeName: '마29',
      brandName: 'ma',
      category: '레더',
      imageUrl: '',
      option: '오 드 퍼퓸',
      price: 240000,
      capacity: '100ml',
      scraped: true,
    },
    {
      id: 6,
      perfumeName: '바29',
      brandName: 'Ba',
      category: '레더',
      imageUrl: '',
      option: '오 드 퍼퓸',
      price: 240000,
      capacity: '100ml',
      scraped: true,
    },
    {
      id: 7,
      perfumeName: '사39',
      brandName: 'sa',
      category: '',
      imageUrl: '',
      option: '오 드 퍼퓸',
      price: 240000,
      capacity: '100ml',
      scraped: true,
    },
    {
      id: 8,
      perfumeName: '아49',
      brandName: 'YA',
      category: '우디',
      imageUrl: '',
      option: '오 드 퍼퓸',
      price: 240000,
      capacity: '100ml',
      scraped: true,
    },
  ],
  count: 8,
  totalPage: 2,
};
